name: Build all projects

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 2 1 * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    strategy:
      matrix:
        version: [ '5.6', '5.7', '8.0', 'latest' ]
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: ./docker_build.sh --version ${{ matrix.version }}
